### ISSUE TITLE
Reconnect after lost connection

### ISSUE THREAD

**Issue by rickAllDev** [256dpi/esp-mqtt#10]
Trying to figure out where my mqtt connection stability is failing and wondering if its at the broker and not the esp32 code. I get mqtt disconnect callbacks every few hours. I've got a monitor task that checks whether mqtt is connected (flag set by mqtt status callback) and, if not, calls esp_mqtt_start. I'm wondering if this is the correct logic. I'm also logging whether or not my wifi connection is failing and that does not seem to be the case.

 - should I be destroying (esp_mqtt_stop?) before trying to re-start?
 - is reconnect logic built into the library

This is the list of messages I'm logging on a regular basis...
I (41036017) wifiMqtt: ESP_MQTT_STATUS_DISCONNECTED
I (41036032) esp_mqtt: esp_mqtt_start: create task
I (41036033) esp_mqtt: esp_mqtt_process: begin connection attempt
I (41036307) esp_mqtt: esp_mqtt_process: connection attempt successful
W (41036307) esp_mqtt: esp_mqtt_start: already running
I (41036308) wifiMqtt: ESP_MQTT_STATUS_CONNECTED
E (42251281) esp_mqtt: lwmqtt_keep_alive: -13
I (42251284) esp_mqtt: esp_mqtt_process: exit task
I (42251284) wifiMqtt: ESP_MQTT_STATUS_DISCONNECTED

Every once in awhile, the log pattern looks like this...
E (29620650) esp_mqtt: lwmqtt_connect: -9
W (29620651) esp_mqtt: esp_mqtt_start: already running
W (29620651) esp_mqtt: esp_mqtt_process: connection attempt failed
W (29620751) esp_mqtt: esp_mqtt_start: already running
W (29620852) esp_mqtt: esp_mqtt_start: already running
W (29620952) esp_mqtt: esp_mqtt_start: already running
W (29621052) esp_mqtt: esp_mqtt_start: already running
W (29621152) esp_mqtt: esp_mqtt_start: already running
W (29621252) esp_mqtt: esp_mqtt_start: already running
W (29621352) esp_mqtt: esp_mqtt_start: already running
W (29621453) esp_mqtt: esp_mqtt_start: already running
W (29621554) esp_mqtt: esp_mqtt_start: already running
W (29621654) esp_mqtt: esp_mqtt_start: already running
I (29621654) esp_mqtt: esp_mqtt_process: begin connection attempt
I (29621891) esp_mqtt: esp_mqtt_process: connection attempt successful
W (29621892) esp_mqtt: esp_mqtt_start: already running
I (29621892) wifiMqtt: ESP_MQTT_STATUS_CONNECTED
E (31869026) esp_mqtt: lwmqtt_keep_alive: -13
I (31869029) esp_mqtt: esp_mqtt_process: exit task
I (31869030) wifiMqtt: ESP_MQTT_STATUS_DISCONNECTED
I (31869031) wifiMqtt: CAN'T PUBLISH MQTT - not connected
I (31869093) esp_mqtt: esp_mqtt_start: create task
I (31869094) esp_mqtt: esp_mqtt_process: begin connection attempt
I (31873966) esp_mqtt: esp_mqtt_process: connection attempt successful
W (31873966) esp_mqtt: esp_mqtt_start: already running
I (31873966) wifiMqtt: ESP_MQTT_STATUS_CONNECTED
E (31875971) esp_mqtt: lwmqtt_subscribe_one: -9
E (33849447) esp_mqtt: lwmqtt_keep_alive: -13
I (33849450) esp_mqtt: esp_mqtt_process: exit task
I (33849451) wifiMqtt: ESP_MQTT_STATUS_DISCONNECTED
I (33849455) wifiMqtt: CAN'T PUBLISH MQTT - not connected
I (33849467) esp_mqtt: esp_mqtt_start: create task
I (33849468) esp_mqtt: esp_mqtt_process: begin connection attempt
I (33849894) esp_mqtt: esp_mqtt_process: connection attempt successful
W (33849895) esp_mqtt: esp_mqtt_start: already running
I (33849895) wifiMqtt: ESP_MQTT_STATUS_CONNECTED

**Comment by 256dpi** [comment]
Reconnection is built in. A connection attempt is made every second. What broker are you using?

**Comment by rickAllDev** [comment]
I'm currently use mosquitto. will switch over to a cloud service sometime in the next month or so. 

So does that mean I should not call a re-start on lost-connection callback?

**Comment by 256dpi** [comment]
Yes. The following example illustrates the correct usage: https://github.com/256dpi/esp-mqtt/blob/master/test/main/main.c.

**Comment by rickAllDev** [comment]
Ok - is there a hook/attribute somewhere in the code that would help me figure out why I'm getting the occasional disconnect?

fyi - haven't had that much experience with the library yet but I really appreciate the ease which it can be integrated into esp32. thanks

**Comment by 256dpi** [comment]
Not at the moment. I would recommend to add some `ESP_LOG` calls in the checked out source code and reset the repository once you are done. ✌️ 

I have to say, in my experience the esp32 has not the most stable wifi connection. I usually also see some disconnects in my projects. Possibly the upcoming v3 release of `esp-idf` will also fixe some underlying bugs.

**Comment by rickAllDev** [comment]
Ok, I will add some debug stuff. 

On the esp32, I agree on the instability although I've been using latest version for awhile and it seems much more stable. While I seem to be losing the mqtt connection occasionally, my wifi does not seem to be dropping out which is why I'm focused on the broker at the moment. I may just switch to a cloud broker and see if the instability continues.
