### ISSUE TITLE
Initializing NVS before WIFI 

### ISSUE THREAD

**Issue by cmbahadir** [256dpi/esp-mqtt#14]
Hi Joël,

wifi_init error raises at app_main() in test code;

W (57) wifi: wifi nvs_open fail ret=4353
E (59)  wifi: wifi_init 1515 ret=4353

It is required to initialize nvs before wifi init as follows, which worked for me;

    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES) {
      ESP_ERROR_CHECK(nvs_flash_erase());
      ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);

**Reference Issue:**
https://github.com/espressif/arduino-esp32/issues/761

**Comment by 256dpi** [comment]
Thanks! I added the call in a reduced fashion.

**Comment by roysG** [comment]
error: 'nvs_flash_init' was not declared in this scope
Someone knows how to solve it?

**Comment by swapnilam93** [comment]
#include "nvs_flash.h"
