### ISSUE TITLE
Max library MQTT message recieve size?

### ISSUE THREAD

**Issue by ghost** [256dpi/esp-mqtt#19]
Hi :)

I am using Mosquitto (V.1.14) as an MQTT broker. From the broker, if i am sending a string longer than 236 char in length to a topic which my ESP32 is subscribed it makes the MQTT client on ESP32 disconnect 
(`lwmqtt_yield -1`).

 Is this normal? If it would be normal my understanding is that the lwmqtt max buffer size is 256 bytes so 236 bytes for data and 20 bytes for message header. Is this a problem from my side or the library is limited in terms of data size recieved bigger than 236 bytes?

See attached picture for ESP32 logging.

*I am using almost the exact code as the example provided in the repo. On the image provided, you can see recieved message size in parentheses ( ). It crashes  (`lwmqtt_yield -1`) when i send a message of 237 bytes in length.

Regards,
ogensyts

![espmqtt](https://user-images.githubusercontent.com/18515700/39963980-1ad8d25c-5648-11e8-8d04-1e940874401c.PNG)

**Comment by 256dpi** [comment]
In order to receive and send more data, you need to increase the buffer size: 

```c++
void esp_mqtt_init(esp_mqtt_status_callback_t scb, esp_mqtt_message_callback_t mcb,
                   size_t buffer_size, int command_timeout);
```

In the included example it is set to 256, but can be increased if needed.

**Comment by ghost** [comment]
My bad, I did not see that. Thank you! 👍

**Comment by kutaybaDB** [comment]
> 

may you explain the usage of this code please dude ? i think i missed an important library to include so it doesnt working

**Comment by wiless** [comment]
It took more than two hrs to figure out the issue of this limit. Wish there was some error thrown, in the callback.
