### ISSUE TITLE
make include c++ ready

### ISSUE THREAD

**Issue by vortex314** [256dpi/esp-mqtt#2]
The include could be made ready for C++ source inclusion by using 
#ifdef __cplusplus
extern "C" {
#endif
See : https://stackoverflow.com/questions/3789340/combining-c-and-c-how-does-ifdef-cplusplus-work

BTW : nice library, just what I was looking for !

**Comment by vortex314** [comment]
I changed file myself.

**Comment by rickAllDev** [comment]
and this at the bottom...
#ifdef __cplusplus
}
#endif
