### ISSUE TITLE
Security features

### ISSUE THREAD

**Issue by justdominator** [256dpi/esp-mqtt#22]
Hello, 

How I can implement some encryption with your code? Unfortunately, there are not some public examples or descriptions for this kind of issue.

Please, give me some point where I can start from. Thanks.

**Comment by 256dpi** [comment]
Thanks for your interest! Unfortunately, TLS encryption is not yet supported. To enable support, we would need to add new API and internal drivers to use the ESP-IDF TLS libraries. I'm happy to review contributions to add this feature!

**Comment by kshyshkin** [comment]
Hello. May be you can give some tips how integrate tls support to your library?

**Comment by 256dpi** [comment]
The process would be to copy `esp_lwmqtt.c` to e.g `esp_tls_lwmqtt.c` and implement all callbacks using the ESP-IDF TLS library. AFAIK they offer openSSL and mbedTLS, so we would need to decide which one to use.

After that, I would implement a method that configures the client using the TLS callbacks.
