### ISSUE TITLE
Error -6 and -13 on sending larger (up to 37kB) chunks of data

### ISSUE THREAD

**Issue by Thomseeen** [256dpi/esp-mqtt#26]
I'm sending data with up to 37kB (a jpg picture) to a mosquitto-broker. Before each such package I send a timestemp with 5bytes. The timestamp always reaches the broker while the picture only sometimes gets sent.
When the picture doesn't get sent succesfully I get this error:
```
E (52275) esp_mqtt: lwmqtt_publish: -6
```
Occasionally I get
```
Task watchdog got triggered. The following tasks did not reset the watchdog in time:
 - IDLE (CPU 1)
Tasks currently running:
CPU 0: IDLE
CPU 1: esp_mqtt
E (75785) esp_mqtt: lwmqtt_keep_alive: -13
```
directly after I tried to send the picture and it failed and sometimes the error 13 just gets thrown randomly without any traffic happening (mosquitto is of course still running to handle the pings).
The third error I noticed is an error on reconnect:
```
I (75795) esp_mqtt: esp_mqtt_process: begin connection attempt
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x40136893  PS      : 0x00060e30  A0      : 0x801325b1  A1      : 0x3ffe1290
A2      : 0xffffffff  A3      : 0x00009088  A4      : 0x00000010  A5      : 0x00000000
A6      : 0x0000abab  A7      : 0x00000038  A8      : 0x3ffe12bc  A9      : 0x00000000
A10     : 0x00001dd8  A11     : 0x3ffc13cc  A12     : 0x00000000  A13     : 0x00000001
A14     : 0x0000abab  A15     : 0x00000000  SAR     : 0x0000001c  EXCCAUSE: 0x0000001d
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000

Backtrace: 0x40136893:0x3ffe1290 0x401325ae:0x3ffe12b0 0x40132384:0x3ffe1300 0x400d3bcd:0x3ffe1350

Rebooting...
```

The buffer size given to `esp_mqtt_init` is 37kB and the timeout 15000ms. I regularly check wether the heap has large enough blocks to handle the data and there are always blocks left with >60kB.

My code can be found at [repository](https://github.com/Thomseeen/Summerschool.MQTT_Doorbell_Demo).

**Comment by 256dpi** [comment]
Did you find a solution to your problem in the end?

**Comment by Thomseeen** [comment]
I tried to pin it down more exactly and found a few problems regarding the memory usage. Those problems weren't exactly at your side so I closed the issue. But I can list two things I changed in your code to make it work better for me.

- I increased the `option.keep_alive` to 60
- I error checked the creation of your `esp_mqtt_process` task and put it in a delayed `while`-loop to retry until enough memory has been freed. I was running into errors because there wasn't enough memory left for the task to be created so the mqtt-client didn't start properly and I would have had to call `esp_mqtt_start` repeatedly. There should always be enough memory but in some cases the IDLE-task needs to be given some time to free it before the mqqt-task can use it.
```C
// create mqtt thread
    BaseType_t err = pdFAIL;
    while (err != pdPASS) {
        ESP_LOGI(ESP_MQTT_LOG_TAG, "esp_mqtt_start: biggest free heap-block is %d bytes", heap_caps_get_largest_free_block(MALLOC_CAP_8BIT));  // heapcontrol
        ESP_LOGI(ESP_MQTT_LOG_TAG, "esp_mqtt_start: create task");
        err = xTaskCreatePinnedToCore(esp_mqtt_process, "esp_mqtt", CONFIG_ESP_MQTT_TASK_STACK_SIZE, NULL, CONFIG_ESP_MQTT_TASK_STACK_PRIORITY, &esp_mqtt_task, 1);
        // BaseType_t err = xTaskCreate(esp_mqtt_process, "esp_mqtt", CONFIG_ESP_MQTT_TASK_STACK_SIZE, NULL, CONFIG_ESP_MQTT_TASK_STACK_PRIORITY, &esp_mqtt_task);
        if (err != pdPASS) {
            ESP_LOGE(ESP_MQTT_LOG_TAG, "esp_mqtt_start: error while creating esp_mqtt_process task %d", err);
        }
        vTaskDelay(500 / portTICK_PERIOD_MS);
    }
    ESP_LOGI(ESP_MQTT_LOG_TAG, "esp_mqtt_start: biggest free heap-block is %d bytes", heap_caps_get_largest_free_block(MALLOC_CAP_8BIT));  // heapcontrol
    // set local flag
    esp_mqtt_running = true;
```

It is working better but noew I get the `lwmqtt -4` error quite often with various `command_timeout` lengths. As this doesn't really fit in the issue and I don't have too much time to look into it at the moment I didn't open a new issue (yet).

**Comment by X-Ryl669** [comment]
Seems like it's related to [this](https://github.com/espressif/esp-idf/commit/a9e63d947bc864a2aaa30389c911777f362f93b1). Make sure you have the latest esp-idf code (it's a shame such basic stuff only entered the repository a month ago).

**Comment by 256dpi** [comment]
@X-Ryl669 Thanks for sharing!
