### ISSUE TITLE
How does it compare to "official" esp-mqtt ?

### ISSUE THREAD

**Issue by X-Ryl669** [256dpi/esp-mqtt#29]
Since there is already a MQTT client in esp-idf, how does this software compare to the idf's client ?
I'm asking for speed / memory usage / flash size / features numbers here, if you have them.
Thanks!

**Comment by 256dpi** [comment]
The official component matured quite a bit and offers some additional features like WebSocket support and more TLS options. But, I never used it so I really don't know.

What I do now: This implementation uses a lot of the async API's provided by LWIP and should therefore be quite responsive. Also the code and the used low-level library LWMQTT are pretty well documented.

If you have the time I'd love to see a thorough analysis of the matter!  :-)
