### ISSUE TITLE
esp-open-rtos: Not able to publish from another task

### ISSUE THREAD

**Issue by nitishpareek1** [256dpi/esp-mqtt#4]
Hi All,

I have created following task:

xTaskCreate(&wifi_task, "wifi_task", 256, NULL, 2, NULL);
xTaskCreate(&mqtt_task, "mqtt_task", 2048, NULL, 2, NULL);
xTaskCreate(buttonPollTask, "buttonPollTask", 1048, NULL, 2, NULL);

I have initialize aws mqtt from task mqtt_task and trying to publish data from another task buttonPollTask. I have taken mqtt_client_t as a static global but unfortunately, failed to publish. It's not even connected.

But if i create only one task mqtt_task then it is publishing perfectly with the static global mqtt_client_t.

can anyone help in this case?

Thanks in advance.

**Comment by 256dpi** [comment]
Can you post some code?

**Comment by 256dpi** [comment]
Closed as issue is stale.
