### ISSUE TITLE
assert failed!. Why is task pinned to core 1?

### ISSUE THREAD

**Issue by rickAllDev** [256dpi/esp-mqtt#8]
Had the 'assert failed!' issue when esp_mqtt_start was called.

Was wondering what the rationale is for pinning to core 1. You might want to change so that either core (or no core) can be defined. Easy enough for me to change but I hate modifying libraries since it makes maintenance much more difficult.

**Comment by 256dpi** [comment]
Yes, I want to make this configurable via Kconfig in the future.
